### YamlMime:Role 
title: Engenheiro DevOps
metadata: 
  title: Engenheiro DevOps
  description: Os Engenheiros DevOps combinam pessoas, processos e tecnologias para oferecer continuamente produtos e serviços valiosos que atendam às necessidades do usuário final e aos objetivos de negócios. 
uid: role.devops-engineer 
summary: | 
  Os Engenheiros DevOps combinam pessoas, processos e tecnologias para oferecer continuamente produtos e serviços valiosos que atendam às necessidades do usuário final e aos objetivos de negócios.
subTitle: Os Engenheiros DevOps combinam pessoas, processos e tecnologias para oferecer continuamente produtos e serviços valiosos que atendam às necessidades do usuário final e aos objetivos de negócios.
certificationPaths: 
- title: Azure DevOps Engineer
  linkedInKeywords: Azure DevOps Engineer
  uid: certification-path.devops 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.devops-engineer
    levels:
    - advanced    
certifications:
- uid: certification.devops-engineer
  requiredExams:
  - uid: exam.az-400
resources:
- title: Guia de Treinamento e Certificações Microsoft
  description: Explore todas as certificações em um guia conciso de treinamento e certificações.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Cartaz de Treinamento e Certificações
  description: Escolha seu caminho para o sucesso com este cartaz de treinamento e certificações.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Apoio às certificações
  href: ../help.md
  description: Obtenha ajuda por meio de fóruns de suporte de Certificação da Microsoft. O moderador do fórum responderá em um dia útil, de segunda a sexta-feira.
