### YamlMime:Role 
title: Functional Consultant 
metadata: 
  title: Functional Consultant 
  description: Os Functional Consultants aproveitam o Microsoft Dynamics 365 e a Microsoft Power Platform para antecipar e planejar as necessidades do cliente. 
uid: role.functional-consultant 
summary: | 
  Os Functional Consultants aproveitam o Microsoft Dynamics 365 e a Microsoft Power Platform para antecipar e planejar as necessidades do cliente.
subTitle: Os Functional Consultants aproveitam o Microsoft Dynamics 365 e a Microsoft Power Platform para antecipar e planejar as necessidades do cliente.
certificationPaths: 
- title: Dynamics 365 Customer Service Functional Consultant
  linkedInKeywords: Dynamics 365 Customer Service Functional Consultant
  uid: certification-path.d365-functional-consultant-customer-service 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
    
- title: Dynamics 365 Field Service Functional Consultant
  linkedInKeywords: Dynamics 365 Field Service Functional Consultant
  uid: certification-path.d365-functional-consultant-field-service 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate

- title: Dynamics 365 Finance Functional Consultant
  linkedInKeywords: Dynamics 365 Finance Functional Consultant
  uid: certification-path.d365-functional-consultant-financials 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate


- title: Dynamics 365 Manufacturing Functional Consultant
  linkedInKeywords: Dynamics 365 Manufacturing Functional Consultant
  uid: certification-path.d365-functional-consultant-manufacturing
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate

- title: Dynamics 365 Marketing Functional Consultant
  linkedInKeywords: Dynamics 365 Marketing Functional Consultant
  uid: certification-path.d365-functional-consultant-marketing 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate

- title: Dynamics 365 Sales Functional Consultant
  linkedInKeywords: Dynamics 365 Sales Functional Consultant
  uid: certification-path.d365-functional-consultant-sales 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate

- title: Dynamics 365 Supply Chain Management Functional Consultant
  linkedInKeywords: Dynamics 365 Supply Chain Management Functional Consultant
  uid: certification-path.d365-functional-consultant-supply-chain-management
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate

certifications:
- uid: certification.d365-functional-consultant-customer-service
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-230  

- uid: certification.d365-functional-consultant-field-service
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-240

- uid: certification.d365-functional-consultant-financials
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-310  


- uid: certification.d365-functional-consultant-manufacturing
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-320  

- uid: certification.d365-functional-consultant-marketing
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-220  

- uid: certification.d365-functional-consultant-sales
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-210  

- uid: certification.d365-functional-consultant-supply-chain-management
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-330  
- uid: certification.power-platform-functional-consultant-associate
  requiredExams:
  - uid: exam.pl-200  
- uid: certification.d365-business-central-functional-consultant-associate
  requiredExams:
  - uid: exam.mb-800
resources:
- title: Guia de Treinamento e Certificações Microsoft
  description: Explore todas as certificações em um guia conciso de treinamento e certificações.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Cartaz de Treinamento e Certificações
  description: Escolha seu caminho para o sucesso com este cartaz de treinamento e certificações.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Suporte para certificações
  href: ../help.md
  description: Obtenha ajuda através dos fóruns de suporte da Microsoft Certification. O moderador do fórum responderá em um dia útil, de segunda a sexta-feira.
