### YamlMime:Role 
title: Solutions Architect 
metadata: 
  title: Solutions Architect
  description: Os Solution Architects têm experiência em computação, rede, armazenamento e segurança. 
uid: role.solution-architect  
summary: | 
  Os Solution Architects têm experiência em computação, rede, armazenamento e segurança.
subTitle: Os Solution Architects têm experiência em computação, rede, armazenamento e segurança.
certificationPaths: 
- title: Azure Solutions Architect
  linkedInKeywords: Azure Solutions Architect
  uid: certification-path.azure-solutions-architect 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-solutions-architect
    levels:
    - advanced    
- title: Dynamics 365 Finance and Operations Apps Solution Architect
  linkedInKeywords: Dynamics 365 Finance and Operations Apps Solution Architect
  uid: certification.d365-finance-and-operations-apps-solution-architect-expert
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate  
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate 
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate 
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate 
  - uid: certification.d365-finance-and-operations-apps-solution-architect-expert
    levels:
    - advanced  
- title: Power Apps + Dynamics 365 Solution Architect
  linkedInKeywords: Power Apps + Dynamics 365 Solution Architect
  uid: certification.power-apps-and-d365-solution-architect-expert
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-apps-and-d365-developer-associate
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate
  - uid: certification.power-apps-and-d365-solution-architect-expert
    levels:
    - advanced
certifications:
- uid: certification.azure-solutions-architect
  requiredExams:
  - uid: exam.az-303
  - uid: exam.az-304
- uid: certification.d365-finance-and-operations-apps-solution-architect-expert
  requiredExams:
  - uid: exam.mb-700
- uid: certification.power-apps-and-d365-solution-architect-expert
  requiredExams:
  - uid: exam.mb-600
- uid: certification.azure-for-sap-workloads-specialty
  requiredExams:
  - uid: exam.az-120
resources:
- title: Guia de Treinamento e Certificações Microsoft
  description: Explore todas as certificações em um guia conciso de treinamento e certificações.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Cartaz de Treinamento e Certificações
  description: Escolha seu caminho para o sucesso com este cartaz de treinamento e certificações.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Suporte para certificações
  href: ../help.md
  description: Obtenha ajuda através dos fóruns de suporte da Microsoft Certification. O moderador do fórum responderá em um dia útil, de segunda a sexta-feira.
