### YamlMime:Certification
title: 'MCSE: Business Applications'
metadata:
  title: 'MCSE: Business Applications'
  description: 'MCSE: Business Applications'
uid: certification.mcse-business-applications
iconUrl: /media/learn/certification/badges/mcse-badge.svg
summary: |-
  <div>
  <div><font color='red'><strong>Devido ao surto de coronavírus (COVID-19), a Microsoft está implementando várias mudanças temporárias em nosso programa de treinamento e certificação. <a href='https://www.microsoft.com/en-us/learning/community-blog-post.aspx?BlogId=8&amp;Id=375289'>Saiba mais</a>.</strong></font><br/><br/></div>
  <div><strong>Esta certificação será desativada em domingo, 31 de janeiro de 2021. Não será mais possível obter esta certificação após esta data. Todas as certificações que você obtiver antes das datas de desativação continuarão visíveis em sua transcrição no <a href='https://www.microsoft.com/learning/dashboard.aspx'>Painel de Certificação</a>. Além disso, é possível <a href='/learn/certifications/retired-certifications'>pesquisar todas as certificações desativadas</a>.</strong><br/><br/></div>
  </div>

  Esta certificação valida que você tem os conhecimentos necessários para trabalhar e gerenciar as tecnologias Microsoft Dynamics 365. Você começará com uma fundamentação em Microsoft Dynamics 365 e demonstrar conhecimentos adicionais em uma ou mais áreas específicas de negócios.

  Para obter a certificação Business Applications do MCSA, você deve preencher os seguintes requisitos&#58;
  - Obter a certificação de pré-requisito&#58; [MCSA&#58; Microsoft Dynamics 365 for Operations](/learn/certifications/mcsa-microsoft-dynamics-365-for-operations)
  - Deverá ser aprovado em um dos seguintes exames&#58;
    - [MB2-716&#58; Microsoft Dynamics 365 Customization and Configuration](/learn/certifications/exams/mb2-716)
    - [MB6-897&#58; Microsoft Dynamics 365 for Retail](/learn/certifications/exams/mb6-897)
    - [MB6-898&#58; Microsoft Dynamics 365 for Talent](/learn/certifications/exams/mb6-898)
subTitle: Esta certificação valida que você tem os conhecimentos necessários para trabalhar e gerenciar as tecnologias Microsoft Dynamics 365. Você começará com uma fundamentação em Microsoft Dynamics 365 e demonstrar conhecimentos adicionais em uma ou mais áreas específicas de negócios.
levels:
- beginner
skills:
- none
roles:
- business-analyst
type: mcse
products:
- dynamics
exams:
- uid: exam.mb-2-716
- uid: exam.mb-6-897
- uid: exam.mb-6-898
prerequisites:
- uid: certification.mcsa-microsoft-dynamics-365-for-operations
  isOptional: false
resources:
- title: Training and certification guide
  description: Explore todas as certificações em um guia conciso de treinamento e certificações.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Cartaz de certificação
  description: Verifique a visão geral dos fundamentos, certificações baseadas em funções e especialidades.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Exam Replay
  description: Veja duas grandes ofertas para ajudar a aumentar suas chances de sucesso.
  href: deals.md
- title: Suporte para certificações
  description: Obtenha ajuda através dos fóruns de suporte da Microsoft Certification. O moderador do fórum responderá em um dia útil, de segunda a sexta-feira.
  href: help.md
- title: Painel de certificação
  description: Revise e gerencie seus compromissos, certificados e transcrições agendados.
  href: https://www.microsoft.com/learning/dashboard.aspx

